config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :repairs
  resources :clients
  resources :phone_models
 
  root 'repairs#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  has_many :repairs

  validates :last_name, :first_name, :phone_number, presence: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  def full_name
    last_name + ' ' + first_name
  end
end

app/models/concerns/date_utils.rb
class DateUtils
  def self.simple_date(datetime)
    datetime.try(:strftime, "%d/%m/%Y")
  end
end

app/models/phone_model.rb
class PhoneModel < ActiveRecord::Base

  has_many :repairs

  validates :name, presence: true
  
end

app/models/repair.rb
class Repair < ActiveRecord::Base

  belongs_to :phone_model
  belongs_to :client

  validates :phone_model, :client, :status, :imei, presence: true

  attr_accessor :tag_list_array, :tag_list_string

  acts_as_taggable # basic usage - gives us 'tags'

  state_machine :status, :initial => :in_repair do 

    event :fix do 
      transition :in_repair => :fixed, :sent_to_service => :fixed, :not_repairable => :fixed
    end

    event :send_to_service do 
      transition :in_repaire => :sent_to_service
    end

    event :cant_repair do 
      transition :in_repaire => :not_repairable, :sent_to_service => :not_repairable
    end
  end

  def tag_list_array=(tags)
    self.tag_list += tags.join(",")
    logger.info "XXX #{tag_list}"
  end

  def tag_list_string=(tags)
    self.tag_list += tags
    logger.info "XXX #{tag_list}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: 'Client was successfully created.'
    else 
      render :new
    end
  end

  def edit
  end

  def destroy
    @client.destroy
  end


  private

  def set_client
   @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:last_name, :first_name, :phone_number, :email)
  end

end

app/controllers/phone_models_controller.rb
class PhoneModelsController < ApplicationController
    before_action :set_phone_models, only: [:show, :edit, :update, :destroy]

  def index
    @phone_models = PhoneModel.all
  end

  def show
  end

  def new
    @phone_model = PhoneModel.new
  end

  def create
    @phone_model = PhoneModel.new(phone_model_params)

    if @phone_model.save
      head :created
    else
      render json:@phone_model.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @phone_model.destroy
  end


  private

  def set_phone_models
   @phone_model = PhoneModel.find(params[:id])
  end

  def phone_model_params
    params.require(:phone_model).permit(:name)
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]


  def index
    @repairs = Repair.order(:deadline)
  end

  def show
  end

  def new
    @repair = Repair.new
    @repair.relased ||= false
    
    @client = Client.new
    @phone_model = PhoneModel.new
  end

  def create
    @repair = Repair.new(repair_params)

    if @repair.save
      redirect_to @repair, notice: 'Repair was successfully created.'
    else 
      @phone_model = PhoneModel.new #to do implements
      @client = Client.new #to do implements
      render :new
      end
  end

  def edit
  end

  def destroy
    @repair.destroy
  end

  def date
    self.Date.commercial
  end



  private

  def set_repair
   @repair = Repair.find(params[:id])
  end

  def repair_params
    params.require(:repair).permit(:phone_model_id, :client_id, :status, :imei, :servicemac_id, :max_price, :cost, :price, :deadline, :description, :description_service, :description_client, :relased, :tag_list_string , :tag_list_array => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/date_helper.rb
module DateHelper
  def simple_date(datetime)
    DateUtils.simple_date(datetime)
  end
end

app/helpers/phone_models_helper.rb
module PhoneModelsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Service GSM</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="top-bar" data-topbar role="navigation"> 
      <ul class="title-area"> 
        <li class="name"><h1><%= link_to 'Service GSM', root_path %></li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section"> <!-- Right Nav Section --> 
        <ul class="right"> 
          <li class="active"><a href="#">Right Button Active</a></li> 
          <li class="has-dropdown"><a href="#">Right Button Dropdown</a> 
            <ul class="dropdown"> 
              <li><a href="#">First link in dropdown</a></li> 
              <li class="active"><a href="#">Active link in dropdown</a></li> 
            </ul> 
          </li> 
        </ul> 
      </section> 
    </nav>

    <div class="small-2 large-2 columns">
      <ul class="side-nav"> 
        <li><%= link_to new_repair_path do %>
        <i class="fa fa-plus"></i>Add new repair
        <% end %></li>
        <li><%= link_to repairs_path do %>
        <i class="fa fa-arrow-right"></i>In progess
        <% end %></li>
        <li><%= link_to repairs_path do %>
        <i class="fa fa-arrow-left"></i>Relased
        <% end %></li>
        <li><%= link_to repairs_path do %>
        <i class="fa fa-file-text"></i>History
        <% end %></li>
      </ul>
    </div>

    <div class="small-4 large-10 columns">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/repairs/_client.html.erb
<div id="new_client">
  <h4>New client</h4>
  <%= simple_form_for @client , :remote => true do |client| %>
    <%= client.input :last_name %>
    <%= client.input :first_name %>
    <%= client.input :phone_number %>
    <%= client.input :email %>
fdsfdsf
    <%= client.button :submit %>

  <% end %>
  aaaaaaaaaaaaa
</div>

app/views/repairs/_form.html.erb
<%= simple_form_for(@repair) do |repair| %>

  <%= repair.input :status %>
  <%= repair.input :imei, placeholder: '000000000000' %>
  <%= repair.input :serviceman_id%>
  <%= repair.input :description %>
  <%= repair.input :max_price %>
  <%= repair.input :costs %>
  <%= repair.input :price %>
  <%= repair.input :deadline %>

  <%= repair.button :submit %>

<% end %>

app/views/repairs/_phone.html.erb
<div id="new_phone">
  <h4>New model</h4>
  <%= simple_form_for @phone_model, :remote => true do |phone| %>
    <%= phone.input :name %>
    <%= phone.error :name %>
    <%= phone.button :submit, class: 'btn btn-success'%>
  <% end %>
</div>

app/views/repairs/_repair.html.erb
<div>
  <%= simple_form_for(@repair) do |repair| %>
    <h2>Phone</h2>
    <%= repair.input :phone_model_id,  label: false, :collection => PhoneModel.all, :label_method => :name, :value_method => :id %>
    <a href="#" class="button small" id="add_phone">Add new phone model</a>
    <h2>Client</h2>
    <%= repair.input :client_id, label: false, :collection => Client.all, :label_method => :full_name, :value_method => :id %>
    <a href="#" class="button small" id="add_client">Add new client</a>
    <%= repair.input :imei, placeholder: '000000000000' %>
    <%= repair.input :tag_list_array, :as => :check_boxes, :collection => ['screen', 'simlock', 'language', 'soft'], :label => "Description" %>
    <%= repair.input :tag_list_string, label: false, placeholder: 'Other descriptions (separated by commas)' %>
    <%= repair.input :description_service %>
    <%= repair.input :description_client %>
    <%= repair.input :max_price %>
    <%= repair.input :deadline, as: :string, input_html: { class: "datepicker" } %>

    <%= repair.button :submit, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/repairs/destroy.html.erb
<h1>Repairs#destroy</h1>
<p>Find me in app/views/repairs/destroy.html.erb</p>

app/views/repairs/index.html.erb
<table class="display" id="repairs">
  <thead>
    <tr>
      <th>Created date</th>
      <th>Deadline</th>
      <th>Phone model</th>
      <th>Client</th>
      <th>Description</th>
      <th>Status</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= simple_date(repair.created_at) %></td>
        <td><%= simple_date(repair.deadline) %></td>
        <td><%= repair.phone_model.name %></td>
        <td><%= repair.client.full_name %></td>
        <td><%= repair.tag_list %></td>
        <td><%= repair.status %></td>
        <td><%= repair.price %></td>
               

        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/repairs/new.html.erb
<%= content_tag :div, class: "large-4 columns" do -%>
  <%= render 'repair' %>
<% end -%>

<%= content_tag :div, class: "large-4 large-offset-1 columns left" do -%>

  <%= render 'phone' %>
  <%= render 'client' %>

<% end -%>

app/views/repairs/show.html.erb
<div class="col-sm-4">
  <h2>Phone model</h2>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Phone model</label>
    <div  class="field_border"><%= @repair.phone_model.name %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Imei</label>
    <div  class="field_border"><%= @repair.imei %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Status</label>
    <div  class="field_border"><%= @repair.status %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Serviceman</label>
    <div  class="field_border"><%= @repair.serviceman_id %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Tags</label>
    <div  class="field_border"><%= @repair.tag_list %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Created at</label>
    <div  class="field_border"><%= simple_date(@repair.created_at) %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Deadline</label>
    <div  class="field_border"><%= simple_date(@repair.deadline) %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Description for service</label>
    <div  class="field_border"><%= @repair.description_service %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Description for client</label>
    <div  class="field_border"><%= @repair.description_client %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Max price</label>
    <div  class="field_border"><%= @repair.max_price %></div>
  </div>

  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Costs</label>
    <div  class="field_border"><%= @repair.costs %></div>
  </div>

  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Price</label>
    <div  class="field_border"><%= @repair.price %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Relased</label>
    <div  class="field_border"><%= @repair.relased %></div>
  </div>


</div>

<div class="col-sm-4 col-md-offset-1">
  <h2>Client</h2>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Full name</label>
    <div  class="field_border"><%= @repair.client.full_name %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Phone number</label>
    <div  class="field_border"><%= @repair.client.phone_number %></div>
  </div>
  <div class="form-group string required phone_model_name">
    <label class="string required control-label">Email</label>
    <div  class="field_border"><%= @repair.client.email %></div>
</div>